---
title: "CARAMeL heatmap visualization"
author: "Carolina H. Chung"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_notebook: 
    code_folding: hide
---

This is an R Markdown Notebook for visualizing heatmaps from CARAMeL manuscript. 

# Set up environment

Install and load required pakcages.

```{r install packages, include=F}

# svDialogs (for popup user input)
  install.packages('svDialogs')

# dplyr (for piping functions)
  install.packages('dplyr')

# readxl (for reading Excel files)
  install.packages('readxl')

# pheatmap (for pretty heatmaps)
  if (!require("devtools")) {
    install.packages("devtools", dependencies = TRUE)
    library(devtools)
  }
  install_github("raivokolde/pheatmap")
  
# RColorBrewer (for custom color palettes)
  install.packages('RColorBrewer')

```

```{r load packages, include=F}

  library(svDialogs)
  library(dplyr)
  library(readxl)
  library(pheatmap)
  library(RColorBrewer)
  
```

# Load data 

Load data to visualize. Specifically: 

- *E. coli* drug-media interactions (Biolog)
- *E. coli* CARAMeL model predictions

```{r load data}

# Create dataset variable
  dataset <- list()
  
# EC (Biolog)
  dataset$EC$bio <- read_excel('results/plot_data.xlsx', sheet='ecoli_biolog')
  
# EC (predictions)
  dataset$EC$pred <- read_excel('results/plot_data.xlsx', 
                                sheet='pred2_heatmap')
  dataset$EC$pred3 <- read_excel('results/plot_data.xlsx', 
                                sheet='pred3_heatmap')
  dataset$EC$predp <- read_excel('results/plot_data.xlsx', 
                                sheet='popFBA_heatmap')
  
# popFBA
  dataset$popFBA$flux <- read_excel('results/plot_data.xlsx', 
                                    sheet='popFBA_flux')
  
# entropy
  dataset$entropy <- read_excel('results/plot_data.xlsx', sheet='entropy')
  
# Color palette
  col <- c(brewer.pal(9, 'Set1'), brewer.pal(3, 'Accent'))
  
# Save plots?
  save.plot <- dlgInput("Save heatmaps? (T/F)", Sys.info()['F'])$res %>% 
    as.logical(.)

```

# Generate plots

Visualize all *E. coli* and *M. tb* results.

```{r E. coli interactions (Biolog), warning = F}

# Re-organize data
  dataset$EC$bio$Media <- dataset$EC$bio$Media %>% 
    factor(., levels=unique(.))
  y <- dataset$EC$bio[, -c(1:2)]
  rownames(y) <- dataset$EC$bio$Media
  
# Define metadata
  gx <- data.frame(Simulated=dataset$EC$bio$Simulatable %>% 
                     factor(., levels=unique(.)))
  rownames(gx) <- rownames(y)
  gy <- data.frame(Subset=c(rep('train', 4), rep('test', 2)) %>% 
                    factor(., levels=unique(.)), 
                   Target=c(rep('Cell wall', 2), 
                            rep('Protein synthesis, 30S', 2), 
                            rep('Multiple mechanisms', 2)) %>% 
                    factor(., levels=unique(.)))
  rownames(gy) <- colnames(y)
  
# Use RedBlue color palette (asymmetric)
  col.pal <- colorRampPalette(colors=c("snow2", "orchid3"),space="Lab")(100)
  
# Define annotation colors
  col.annot <- list(Simulated=c(Yes='limegreen', No='gray'), 
                    Subset=c(train='lightgoldenrod', test='green4'), 
                    Target=c(`Cell wall`='darkorange', 
                             `Protein synthesis, 30S`='turquoise3',
                             `Multiple mechanisms`='sienna'))
  names(col.annot$Simulated) <- levels(gx$Simulated)
  names(col.annot$Subset) <- levels(gy$Subset)
  names(col.annot$Target) <- levels(gy$Target)
  gz <- data.frame(Target=gy$Target)
  rownames(gz) <- rownames(gy)

# Visualize plot
  p1 <- pheatmap(t(y), cluster_rows=F, cluster_cols=F, gaps_row=4, gaps_col=96,
           legend_breaks=c(min(y), 0.5, 1, 1.5, max(y)-0.05), border_color=T,
           legend_labels=c('0','0.5','1','1.5','Respiration'),
           annotation_row=gz, annotation_col=gx, annotation_colors=col.annot,
           color=col.pal, angle_col='90', show_colnames=F, cellheight=15,
           cellwidth=2, main='Drug-media interactions')
  p1
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/biolog_heatmap.tiff', units='in', 
         width=7, height=2.5, res=300)
    print({
      p1
    })
    dev.off()
  }

```

```{r E. coli predictions (2-way), warning = F}

# Re-organize data
  y <- dataset$EC$pred[, -1]
  rownames(y) <- dataset$EC$pred$Pair
  
# Use RedBlue color palette (asymmetric)
  n <- round(100*(max(y) - min(y)))
  x <- n + round(100*min(y))
  col.neg <- colorRampPalette(colors=c("royalblue3", "white"), 
                              space="Lab")(abs(round(100*min(y))))
  col.pos <- colorRampPalette(colors=c("white", "red4"), 
                              space="Lab")(abs(round(100*max(y))))
  col.pal <- c(col.neg, col.pos)

# Visualize plot
  p2 <- pheatmap(y, cluster_rows=F, cluster_cols=F, gaps_col=c(57, 114),
           clustering_distance_rows='manhattan', color=col.pal, 
           legend_breaks=c(min(y)+0.03, 0, max(y)-0.03), border_color=NA, 
           legend_labels=c('Synergy','Neutral','Antagonism'), 
           show_rownames=F, show_colnames=F, cellheight=2, cellwidth=2)
  p2
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/pred2_heatmap.tiff', units='in', 
         width=6.5, height=2.4, res=300)
    print({
      p2
    })
    dev.off()
  }

```

```{r E. coli predictions (3-way), warning = F}

# Re-organize data
  y <- dataset$EC$pred3[, -1]
  rownames(y) <- dataset$EC$pred3$Pair
  
# Use RedBlue color palette (asymmetric)
  n <- round(100*(max(y) - min(y)))
  x <- n + round(100*min(y))
  col.neg <- colorRampPalette(colors=c("royalblue3", "white"), 
                              space="Lab")(abs(round(100*min(y))))
  col.pos <- colorRampPalette(colors=c("white", "red4"), 
                              space="Lab")(abs(round(100*max(y))))
  col.pal <- c(col.neg, col.pos)

# Visualize plot
  p2 <- pheatmap(y, cluster_rows=F, cluster_cols=F, 
                 gaps_col=c(57, 2*57, 3*57, 4*57, 5*57, 6*57),
           clustering_distance_rows='manhattan', color=col.pal, 
           legend_breaks=c(min(y)+0.03, 0, max(y)-0.03), border_color=NA, 
           legend_labels=c('Synergy','Neutral','Antagonism'), 
           show_rownames=F, show_colnames=F, cellheight=1, cellwidth=1)
  p2
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/pred3_heatmap.tiff', units='in', 
         width=7.5, height=2.5, res=300)
    print({
      p2
    })
    dev.off()
  }

```

```{r E. coli predictions (popFBA), warning = F}

# Re-organize data
  x <- dataset$popFBA$flux %>% 
    relocate(colnames(.)[.[1, ]==2], .after=last_col())
  y <- dataset$EC$predp[, -1]
  rownames(y) <- dataset$EC$predp$Pair
  y <- y[, colnames(y) %in% colnames(x)] %>%  .[, colnames(x)[-c(1, 2)]] %>% 
    rbind(x[1, -c(1, 2)], .) %>% 
    relocate(colnames(.)[.[1, ]==2], .after=last_col())
  z1 <- y[-1, colnames(y)[y[1, ]==1]]
  z2 <- y[-1, colnames(y)[y[1, ]==2]]
  y <- cbind(z1[, 1:50], z2[, 1:50])
  
# Use RedBlue color palette (asymmetric)
  n <- round(100*(max(y) - min(y)))
  x <- n + round(100*min(y))
  col.neg <- colorRampPalette(colors=c("royalblue3", "white"), 
                              space="Lab")(abs(round(100*min(y))))
  col.pos <- colorRampPalette(colors=c("white", "red4"), 
                              space="Lab")(abs(round(100*max(y))))
  col.pal <- c(col.neg, col.pos)
  
# Annotations
  Cluster <- data.frame(Cluster=as.character(rep(c(1, 2), each=50)), 
                        row.names=colnames(y))
  annot.pal <- list(Cluster=c('1'='goldenrod', '2'='darkgreen'))

# Visualize plot
  p2 <- pheatmap(y, cluster_rows=F, cluster_cols=F, gaps_col=c(50),
           clustering_distance_rows='manhattan', color=col.pal, 
           legend_breaks=c(min(y)+0.01, 0, max(y)-0.01), border_color=NA, 
           annotation_col=Cluster, annotation_colors=annot.pal, 
           legend_labels=c('Synergy','Neutral','Antagonism'), 
           show_rownames=F, show_colnames=F, cellheight=2, cellwidth=2, 
           main='Predicted interaction scores')
  p2
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/popFBA_heatmap.tiff', units='in', 
         width=5, height=2, res=300)
    print({
      p2
    })
    dev.off()
  }

```

```{r entropy heatmap, warning = F}

# Re-organize data
  z <- dataset$entropy %>% arrange(Hsum)
  x <- z %>% select(Interaction, Class) %>% .[1:171, ]
  y <- z %>% select(Hsum, Hmean) %>% .[1:171, ]
  rownames(y) <- x$Interaction %>% make.unique(.)
  colnames(y) <- c('Sum', 'Mean')
  
# Define metadata
  Class <- data.frame(Class=x$Class, row.names=rownames(y))
  
# Use RedBlue color palette 
  col.neg <- colorRampPalette(colors=c('blue', 'white'), space='Lab')(50)
  col.pos <- colorRampPalette(colors=c('white', 'red4'), space='Lab')(50)
  col.pal <- c(col.neg, col.pos)
  
# # Use custom annotation palette 
#   col <- rev(brewer.pal(dim(unique(Pathway))[1], 'Set3'))
#   names(col) <- unique(Pathway$Pathway)
#   annot.pal <- list(Pathway=col, Cluster=c('1'='goldenrod', '2'='darkgreen'))

# Visualize plot
  p2 <- pheatmap(y, scale='column', show_rownames=F, show_colnames=T, 
           cluster_rows=F, cluster_cols=F, annotation_row=Class, 
           color=col.pal, border_color='gray', 
           cellwidth=15, cellheight=2, main='Entropy feature heatmap')
  p2
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/popFBA_flux.tiff', units='in', 
         width=7, height=3, res=300)
    print({
      p2
    })
    dev.off()
  }

```

```{r popFBA flux, warning = F}

# Re-organize data
  x <- dataset$popFBA$flux %>% select(rxn, subSystem, colnames(y))
  # y <- x[-1, -c(1, 2)]
  y <- x[-1, -c(1, 2)] %>% t(.) %>% scale(.) %>% t(.) %>% 
    as.data.frame(., row.names=make.unique(x$rxn[-1])) %>% 
    arrange()
  # y[y > 2] <- 2; y[y < -2] <- -2
  rownames(y) <- x$rxn[-1] %>% make.unique(.)
  colnames(y) <- colnames(x)[-c(1, 2)]
  
# Define metadata
  Pathway <- data.frame(Pathway=x$subSystem[-1], row.names=rownames(y))
  Cluster <- data.frame(Cluster=as.character(x[1, -c(1, 2)]), 
                        row.names=colnames(y))
  
# Use RedBlue color palette 
  # col.neg <- colorRampPalette(colors=c('blue', 'white'), space='Lab')(50)
  # col.pos <- colorRampPalette(colors=c('white', 'red4'), space='Lab')(50)
  col.neg <- colorRampPalette(colors=c("royalblue3", "white"), 
                              space="Lab")(abs(round(100*min(y))))
  col.pos <- colorRampPalette(colors=c("white", "red4"), 
                              space="Lab")(abs(round(100*max(y))))
  col.pal <- c(col.neg, col.pos)
  
# Use custom annotation palette 
  col <- rev(brewer.pal(dim(unique(Pathway))[1], 'Set3'))
  names(col) <- unique(Pathway$Pathway)
  annot.pal <- list(Pathway=col, Cluster=c('1'='goldenrod', '2'='darkgreen'))

# Visualize plot
  p2 <- pheatmap(y, scale='none', show_rownames=F, show_colnames=F, 
           cluster_rows=T, clustering_distance_rows='manhattan',
           cluster_cols=F, annotation_row=Pathway, annotation_col=Cluster, 
           color=col.pal, annotation_colors=annot.pal, borker_color='gray', 
           cellwidth=2, cellheight=2, gaps_col=match(2, Cluster$Cluster)-1, 
           main='Flux through metabolic reactions', treeheight_row = 0)
  p2
  
# Save plot (if prompted)
  if (save.plot) {
    tiff('results/R_plots/popFBA_flux.tiff', units='in', 
         width=7, height=3, res=300)
    print({
      p2
    })
    dev.off()
  }

```
