

%     index = find(strcmp(order, interType));
%     if index <= numel(confMatStats.Sensitivity)
%         Accuracy = sum(confMatStats.AccuracyInTotal);
%         Error = sum(confMatStats.ErrorInTotal);
%         Sensitivity = confMatStats.Sensitivity(index);
%         Specificity = confMatStats.Specificity(index);
%         Precision = confMatStats.Precision(index);
%         FalsePositiveRate = confMatStats.FalsePositiveRate(index);
%         F1_score = confMatStats.F1_score(index);
%         MatthewsCorrelationCoefficient = ...
%             confMatStats.MatthewsCorrelationCoefficient(index);
%     else
%         Accuracy = sum(confMatStats.AccuracyInTotal);
%         Error = sum(confMatStats.ErrorInTotal);
%         Sensitivity = NaN;
%         Specificity = NaN;
%         Precision = NaN;
%         FalsePositiveRate = NaN;
%         F1_score = NaN;
%         MatthewsCorrelationCoefficient = NaN;
%         if verbose
%             warning(strcat("Could not determine statistics for ", interType))
%         end
%     end

%     results_struct = struct(...
%         'interactionNames', {interactionNames}, ...
%         'interactionScores', interactionScores, ...
%         'interactionClass', {interactionClass}, ...
%         'predScores', predScores, ...
%         'predClass', {predClass}, ...
%         'corrStat', corrStat, ...
%         'corrPvalue', corrPvalue, ...
%         'confMatStats', confMatStats, ...
%         'accuracy', Accuracy, ...
%         'error', Error, ...
%         'sensitivity', Sensitivity, ...
%         'specificity', Specificity, ...
%         'precision', Precision, ...
%         'falsePositiveRate', FalsePositiveRate, ...
%         'f1_score', F1_score, ...
%         'MCC', MatthewsCorrelationCoefficient, ...
%         'synergyAUC', synergyAUC, ...
%         'antagonismAUC', antagonismAUC, ...
%         'MLmethod', MLmethod);
